### ISSUE TITLE
Issues with Snippets

### ISSUE THREAD

**Issue by cajunitalian** [1RedOne/PowerShell_XAML#1] opened 2016-06-13 19:37 UTC
So when I run the snippet or any of your other XAML Reader code, I get this output:

```
Unable to load Windows.Markup.XamlReader. Double-check syntax and ensure .net is installed.
You cannot call a method on a null-valued expression.
At C:\Users\mdartez\Desktop\PS-Staging.ps1:35 char:62
+ ... electNodes("//*[@Name]") | %{Set-Variable -Name "WPF$($_.Name)" -Valu ...
+                                                           ~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : InvokeMethodOnNull

You cannot call a method on a null-valued expression.
At C:\Users\mdartez\Desktop\PS-Staging.ps1:35 char:62
+ ... electNodes("//*[@Name]") | %{Set-Variable -Name "WPF$($_.Name)" -Valu ...
+                                                           ~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : InvokeMethodOnNull

You cannot call a method on a null-valued expression.
At C:\Users\mdartez\Desktop\PS-Staging.ps1:35 char:62
+ ... electNodes("//*[@Name]") | %{Set-Variable -Name "WPF$($_.Name)" -Valu ...
+                                                           ~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : InvokeMethodOnNull

You cannot call a method on a null-valued expression.
At C:\Users\mdartez\Desktop\PS-Staging.ps1:35 char:62
+ ... electNodes("//*[@Name]") | %{Set-Variable -Name "WPF$($_.Name)" -Valu ...
+                                                           ~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : InvokeMethodOnNull

Found the following interactable elements from our form
To show the form, run the following
$Form.ShowDialog() | out-null
```

Any ideas here?

I do indeed have .net 4.6.1 installed so I am not sure what the argument is.

**Comment by 1RedOne** [comment] 2016-06-15 02:57
Could you share your XAML?  This is normally caused by Visual Studio artifacts, I can help you get to the bottom of it.

**Comment by cajunitalian** [comment] 2016-06-15 13:57
Sure, here it is:

```
#ERASE ALL THIS AND PUT XAML BELOW between the @" "@
$inputXML = @"
<Window x:Class="WPF_GUI_BranchAutomation.MainWindow"
        xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
        xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
        xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
        xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
        xmlns:local="clr-namespace:WPF_GUI_BranchAutomation"
        mc:Ignorable="d"

        Title="Branch Automation" Height="328.788" Width="403.465">
    <Grid>
        <Grid.ColumnDefinitions>
            <ColumnDefinition/>
        </Grid.ColumnDefinitions>
        <Grid.RowDefinitions>
            <RowDefinition/>
        </Grid.RowDefinitions>
        <Image x:Name="image" HorizontalAlignment="Left" Height="100" Margin="10,10,0,0" VerticalAlignment="Top" Width="100" Source="C:\Users\mdartez\Pictures\icons\metroposh.png"/>
        <TextBlock x:Name="textBlock" HorizontalAlignment="Left" Margin="10,137,0,0" TextWrapping="Wrap" Text="ESXi IP Address of New Host" VerticalAlignment="Top"/>
        <TextBox x:Name="textBox" HorizontalAlignment="Left" Height="23" Margin="10,158,0,0" TextWrapping="Wrap" Text="IP Address" VerticalAlignment="Top" Width="151" TextChanged="textBox_TextChanged"/>
        <Button x:Name="button" Content="Run Script" HorizontalAlignment="Left" Margin="285,244,0,0" VerticalAlignment="Top" Width="100" Height="44" BorderBrush="Black" Background="#FF003B81" Foreground="White"/>
        <TextBox x:Name="textBox1" HorizontalAlignment="Left" Height="23" Margin="10,207,0,0" TextWrapping="Wrap" Text="AccountData" VerticalAlignment="Top" Width="151"/>
        <TextBlock x:Name="textBlock1" HorizontalAlignment="Left" Margin="10,186,0,0" TextWrapping="Wrap" Text="Admin Account UserName" VerticalAlignment="Top" Width="151"/>
        <TextBox x:Name="textBox2" HorizontalAlignment="Left" Height="23" Margin="10,256,0,0" TextWrapping="Wrap" Text="Password" VerticalAlignment="Top" Width="151"/>
        <TextBlock x:Name="textBlock2" HorizontalAlignment="Left" Margin="10,235,0,0" TextWrapping="Wrap" Text="Admin Account Password" VerticalAlignment="Top"/>
        <TextBlock x:Name="textBlock3" HorizontalAlignment="Left" Margin="135,10,0,0" TextWrapping="Wrap" VerticalAlignment="Top" Height="100" Width="250"><Run Text="For Use with the Branch automation Project."/><LineBreak/><Run/><LineBreak/><Run Text="Pre-Req's"/><LineBreak/><Run Text="-ESXi IP Address"/><LineBreak/><Run Text="-USB Drive is Inserted in Host"/></TextBlock>
    </Grid>
</Window>
"@       

$inputXML = $inputXML -replace 'mc:Ignorable="d"','' -replace "x:N",'N'  -replace '^<Win.*', '<Window'

[void][System.Reflection.Assembly]::LoadWithPartialName('presentationframework')
[xml]$XAML = $inputXML
#Read XAML

    $reader=(New-Object System.Xml.XmlNodeReader $xaml)
  try{$Form=[Windows.Markup.XamlReader]::Load( $reader )}
catch{Write-Host "Unable to load Windows.Markup.XamlReader. Double-check syntax and ensure .net is installed."}

#===========================================================================
# Load XAML Objects In PowerShell
#===========================================================================

$xaml.SelectNodes("//*[@Name]") | %{Set-Variable -Name "WPF$($_.Name)" -Value $Form.FindName($_.Name)}

Function Get-FormVariables{
if ($global:ReadmeDisplay -ne $true){Write-host "If you need to reference this display again, run Get-FormVariables" -ForegroundColor Yellow;$global:ReadmeDisplay=$true}
write-host "Found the following interactable elements from our form" -ForegroundColor Cyan
get-variable WPF*
}

Get-FormVariables

#===========================================================================
# Actually make the objects work
#===========================================================================

#Sample entry of how to add data to a field

#$vmpicklistView.items.Add([pscustomobject]@{'VMName'=($_).Name;Status=$_.Status;Other="Yes"})

#===========================================================================
# Shows the form
#===========================================================================
write-host "To show the form, run the following" -ForegroundColor Cyan
'$Form.ShowDialog() | out-null'
```

**Comment by 1RedOne** [comment] 2016-07-12 15:19
Ah, I found the issue.  Line 20 has a property of TextChanged, which is added by Visual Studio at times.  PowerShell can't parse this and throws an error.  If you remove this property, your form will display.  

This uncovers an error in my snippet, which I am now repairing.

**Comment by 1RedOne** [comment] 2016-07-12 15:27
Fixed with the newest commit, thanks for flagging this!

**Closed as completed by 1RedOne** 2016-07-12 15:27 UTC
